/* 
========================================
   scc_error.h 
    : errorcode define 
----------------------------------------
  Softcamp(c).
  2015.10.
========================================
*/

#ifndef __SCC_ERROR_H__
#define __SCC_ERROR_H__

#define SCC_SUCCESS									0

#define SELFTEST									50
#define SCMAIN										100
#define SCCMVP										120
#define SCCIPHER									140
#define SCARIA										160
#define SCSHA										170
#define SCHMACSHA									180
#define SCBIGINT									200
#define SCBIGINTKCDSA								250
#define SCRSA										300
#define SCENTROPY									400
#define SCHASHDRBG									500
#define SCKCDSA										600
#define SCPKEY										700
#define SCASN1										800
#define SCRANDOM									900

#define	SCC_COMMON_ERROR_INVALID_INPUT				-10
#define	SCC_COMMON_ERROR_INTERNAL					-11
#define	SCC_COMMON_ERROR_MALLOC_FAILED				-12

#define	SCC_SELFTEST_ERROR_ENTROPY_COMPARE				-(SELFTEST+1)
#define SCC_SELFTEST_ERROR_ALGORITHM_ARIA_KAT			-(SELFTEST+2)
#define SCC_SELFTEST_ERROR_ALGORITHM_HASH_SHA256_KAT	-(SELFTEST+3)
#define SCC_SELFTEST_ERROR_ALGORITHM_HASH_SHA512_KAT	-(SELFTEST+4)
#define SCC_SELFTEST_ERROR_ALGORITHM_HMAC_SHA256_KAT	-(SELFTEST+5)
#define SCC_SELFTEST_ERROR_ALGORITHM_HMAC_SHA512_KAT	-(SELFTEST+6)
#define SCC_SELFTEST_ERROR_ALGORITHM_RSA_KAT			-(SELFTEST+7)
#define SCC_SELFTEST_ERROR_ALGORITHM_KCDSA_KAT			-(SELFTEST+8)
#define SCC_SELFTEST_ERROR_ALGORITHM_DRBG_KAT			-(SELFTEST+9)
#define SCC_SELFTEST_ERROR_INTEGRITY					-(SELFTEST+10)

#define	SCC_MAIN_ERROR_NOT_IMPLEMENTED				-(SCMAIN+1)
#define	SCC_MAIN_ERROR_SELFTESTCASE_FAILED			-(SCMAIN+3)

#define	SCC_CMVP_ERROR_STATE_NOT_ALLOWED			-(SCCMVP+1)
#define	SCC_CMVP_ERROR_UNKNOWN_STATEID				-(SCCMVP+2)
#define	SCC_CMVP_ERROR_STATE_IN_FINALIZED			-(SCCMVP+3)
#define	SCC_CMVP_CIPHER_ERROR_UNKNOWN_ID			-(SCCMVP+5)
#define	SCC_CMVP_HASH_ERROR_UNKNOWN_ID				-(SCCMVP+7)
#define	SCC_CMVP_ERROR_STATE_IN_ERROR				-(SCCMVP+8)
#define	SCC_CMVP_ERROR_CHECKPARAM_UNKNOWN_MODE		-(SCCMVP+9)
#define	SCC_CMVP_ERROR_CHECKPARAM_UNKNOWN_PADDING	-(SCCMVP+10)
#define	SCC_CMVP_ERROR_NOT_INITIALIZED				-(SCCMVP+11)
#define	SCC_CMVP_ERROR_SELFTEST_FAILED				-(SCCMVP+12)
#define	SCC_CMVP_MAC_ERROR_UNKNOWN_ID				-(SCCMVP+14)
#define	SCC_CMVP_PKEY_ERROR_UNKNOWN_ID				-(SCCMVP+16)
#define	SCC_CMVP_PENC_ERROR_UNKNOWN_ID				-(SCCMVP+18)
#define	SCC_CMVP_SIGN_ERROR_UNKNOWN_ID				-(SCCMVP+20)

#define	SCC_CIPHER_ERROR_UNKNOWN_ID					-(SCCIPHER+1)
#define	SCC_CIPHER_ERROR_UNKNOWN_PADDING			-(SCCIPHER+2)
#define	SCC_CIPHER_ERROR_INVALID_PADDING			-(SCCIPHER+3)
#define	SCC_CIPHER_ERROR_IV_LENGTH					-(SCCIPHER+5)
#define	SCC_CIPHER_ERROR_MODE_SIZE					-(SCCIPHER+6)
#define	SCC_CIPHER_ERROR_KEY_LENGTH					-(SCCIPHER+7)
#define	SCC_CIPHER_ERROR_ENCRYPT_FAILED				-(SCCIPHER+8)
#define	SCC_CIPHER_ERROR_DECRYPT_FAILED				-(SCCIPHER+9)

#define	SCC_ARIA_ERROR_INVALID_INPUT				-(SCARIA+1)
#define	SCC_ARIA_ERROR_KEY_LENGTH					-(SCARIA+2)
#define	SCC_ARIA_ERROR_INVALID_PADDING				-(SCARIA+3)
#define	SCC_ARIA_ERROR_ENCRYPT_FAILED				-(SCARIA+4)
#define	SCC_ARIA_ERROR_IV_LENGTH					-(SCARIA+5)
#define	SCC_ARIA_ERROR_DECRYPT_FAILED				-(SCARIA+6)

#define	SCC_SHA256_ERROR_INVALID_INPUT				-(SCSHA+1)
#define	SCC_SHA256_ERROR_INVALID_INPUTLEN			-(SCSHA+2)
#define	SCC_SHA512_ERROR_INVALID_INPUT				-(SCSHA+3)
#define	SCC_SHA512_ERROR_INVALID_INPUTLEN			-(SCSHA+4)

#define	SCC_HMACSHA256_ERROR_INVALID_INPUT			-(SCHMACSHA+1)
#define	SCC_HMACSHA256_ERROR_INVALID_INPUTLEN		-(SCHMACSHA+2)
#define	SCC_HMACSHA512_ERROR_INVALID_INPUT			-(SCHMACSHA+3)
#define	SCC_HMACSHA512_ERROR_INVALID_INPUTLEN		-(SCHMACSHA+4)

#define SCC_BIGNUM_ERROR_FILE_IO_ERROR              -(SCBIGINT+1)  
#define SCC_BIGNUM_ERROR_BAD_INPUT_DATA             -(SCBIGINT+2) 
#define SCC_BIGNUM_ERROR_INVALID_CHARACTER          -(SCBIGINT+3) 
#define SCC_BIGNUM_ERROR_BUFFER_TOO_SMALL           -(SCBIGINT+4)
#define SCC_BIGNUM_ERROR_NEGATIVE_VALUE             -(SCBIGINT+5) 
#define SCC_BIGNUM_ERROR_DIVISION_BY_ZERO           -(SCBIGINT+6) 
#define SCC_BIGNUM_ERROR_NOT_ACCEPTABLE             -(SCBIGINT+7)
#define SCC_BIGNUM_ERROR_ALLOC_FAILED               -(SCBIGINT+8)

#define SCC_BIGNUMKCDSA_ERROR_VERIFY_FAIL           -(SCBIGINTKCDSA+1) 
#define SCC_BIGNUMKCDSA_ERROR_BUFFER_TOO_SMALL      -(SCBIGINTKCDSA+3) 
#define SCC_BIGNUMKCDSA_ERROR_OVER_MODULUS		    -(SCBIGINTKCDSA+4) 
#define SCC_BIGNUMKCDSA_ERROR_MEMORY_ALLOC_FAILED   -(SCBIGINTKCDSA+5) 
#define SCC_BIGNUMKCDSA_ERROR_BN_NEGATIVE_RESULT    -(SCBIGINTKCDSA+6) 

#define SCC_RSA_ERROR_BAD_INPUT_DATA                -(SCRSA+1) 
#define SCC_RSA_ERROR_INVALID_PADDING               -(SCRSA+2)   
#define SCC_RSA_ERROR_KEY_CHECK_FAILED              -(SCRSA+4)   
#define SCC_RSA_ERROR_PUBLIC_FAILED                 -(SCRSA+5)  
#define SCC_RSA_ERROR_PRIVATE_FAILED                -(SCRSA+6)  
#define SCC_RSA_ERROR_VERIFY_FAILED                 -(SCRSA+7)   
#define SCC_RSA_ERROR_OUTPUT_TOO_LARGE              -(SCRSA+8)  
#define SCC_RSA_ERROR_RNG_FAILED                    -(SCRSA+9)  
#define SCC_RSA_ERROR_MEMORY_ALLOC_FAILED		    -(SCRSA+10)
#define SCC_RSA_ERROR_INTENDED_MSG_LENGTH_TOO_SHORT -(SCRSA+11)
#define SCC_RSA_ERROR_MODULUS_TOO_SHORT			    -(SCRSA+12)
#define SCC_RSA_ERROR_INVALID_SIGNATURE 		    -(SCRSA+13)
#define SCC_RSA_ERROR_INVALID_DATALEN				-(SCRSA+14)
#define SCC_RSA_ERROR_INVALID_KEYLEN				-(SCRSA+15)

#define SCC_ENTROPY_ERROR_BAD_INPUT_DATA            -(SCENTROPY+1)   

#define SCC_HASHDRBG_ERROR_INVALID_INPUT           -(SCHASHDRBG+1)   
#define SCC_HASHDRBG_ERROR_INVALID_INPUTLEN        -(SCHASHDRBG+2)   
#define SCC_HASHDRBG_ERROR_INVALID_LIMITREQ        -(SCHASHDRBG+3)   
#define SCC_HASHDRBG_ERROR_MALLOC_FAILED           -(SCHASHDRBG+4)   

#define SCC_KCDSA_ERROR_INVALID_INPUT			   -(SCKCDSA+1)   
#define SCC_KCDSA_ERROR_INVALID_INPUTLEN		   -(SCKCDSA+2)   
#define SCC_KCDSA_ERROR_MALLOC_FAILED			   -(SCKCDSA+3)
#define SCC_KCDSA_ERROR_INVALID_POINTER			   -(SCKCDSA+4)
#define SCC_KCDSA_ERROR_INVALID_KEYFILE			   -(SCKCDSA+5)
#define SCC_KCDSA_ERROR_INVALID_ALG_PARAMS		   -(SCKCDSA+6)
#define SCC_KCDSA_ERROR_BUFFER_TOO_SMALL		   -(SCKCDSA+7)
#define SCC_KCDSA_ERROR_INVALID_DATALEN			   -(SCKCDSA+8)  
#define SCC_KCDSA_ERROR_INVALID_SIGNATURE_LEN	   -(SCKCDSA+9)
#define SCC_KCDSA_ERROR_VERIFY_FAIL				   -(SCKCDSA+10)
#define SCC_KCDSA_ERROR_INVALID_KEY_LENGTH		   -(SCKCDSA+11)

#define SCC_PKEY_ERROR_UNKNOWN_PKEY_ID			   -(SCPKEY+1)
#define SCC_PKEY_ERROR_UNKNOWN_PENC_ID			   -(SCPKEY+2)
#define SCC_PKEY_ERROR_UNKNOWN_SIGN_ID			   -(SCPKEY+3)

#define SCC_ASN1_ERROR_BAD_DATA					   -(SCASN1+1)
#define SCC_ASN1_ERROR_INVALID_LENGTH			   -(SCASN1+2)

#define SCC_RANDOM_ERROR_INVALID_INPUTLEN		   -(SCRANDOM+1)

#ifdef __cplusplus
extern "C" {
#endif

char * 
SC_GetErrorString(const int errorCode);

#ifdef __cplusplus
}
#endif

#endif
